name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i -g pnpm@6
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: install
        run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts
      - name: build
        id: build
        run: pnpm run build
      - name: lint
        if: (${{ success() }} || ${{ failure() }})
        run: pnpm run lint
      - name: audit
        if: (${{ success() }} || ${{ failure() }})
        run: pnpm audit
      - name: test
        run: pnpm test
